# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import comm_pb2 as comm__pb2


class CommunicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Customer_Process = channel.unary_unary(
                '/Communicator/Customer_Process',
                request_serializer=comm__pb2.Info_Request.SerializeToString,
                response_deserializer=comm__pb2.Info_Response.FromString,
                )
        self.BranchInfo = channel.unary_unary(
                '/Communicator/BranchInfo',
                request_serializer=comm__pb2.BroadCast.SerializeToString,
                response_deserializer=comm__pb2.BroadCast_Response.FromString,
                )


class CommunicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Customer_Process(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BranchInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommunicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Customer_Process': grpc.unary_unary_rpc_method_handler(
                    servicer.Customer_Process,
                    request_deserializer=comm__pb2.Info_Request.FromString,
                    response_serializer=comm__pb2.Info_Response.SerializeToString,
            ),
            'BranchInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.BranchInfo,
                    request_deserializer=comm__pb2.BroadCast.FromString,
                    response_serializer=comm__pb2.BroadCast_Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Communicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Communicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Customer_Process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Communicator/Customer_Process',
            comm__pb2.Info_Request.SerializeToString,
            comm__pb2.Info_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BranchInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Communicator/BranchInfo',
            comm__pb2.BroadCast.SerializeToString,
            comm__pb2.BroadCast_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
