# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncomm.proto\"E\n\x0cInfo_Request\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\x02\x12\r\n\x05money\x18\x02 \x01(\x02\x12\x11\n\tinterface\x18\x03 \x01(\t\"<\n\rInfo_Response\x12\x13\n\x0bnew_balance\x18\x01 \x01(\x02\x12\x16\n\x0eprocess_result\x18\x02 \x01(\t\"I\n\tBroadCast\x12\x16\n\x0e\x62ranch_balance\x18\x01 \x01(\x02\x12\x11\n\tbranch_id\x18\x02 \x01(\x02\x12\x11\n\tinterface\x18\x03 \x01(\t\"#\n\x12\x42roadCast_Response\x12\r\n\x05value\x18\x01 \x01(\x02\x32t\n\x0c\x43ommunicator\x12\x33\n\x10\x43ustomer_Process\x12\r.Info_Request\x1a\x0e.Info_Response\"\x00\x12/\n\nBranchInfo\x12\n.BroadCast\x1a\x13.BroadCast_Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INFO_REQUEST']._serialized_start=14
  _globals['_INFO_REQUEST']._serialized_end=83
  _globals['_INFO_RESPONSE']._serialized_start=85
  _globals['_INFO_RESPONSE']._serialized_end=145
  _globals['_BROADCAST']._serialized_start=147
  _globals['_BROADCAST']._serialized_end=220
  _globals['_BROADCAST_RESPONSE']._serialized_start=222
  _globals['_BROADCAST_RESPONSE']._serialized_end=257
  _globals['_COMMUNICATOR']._serialized_start=259
  _globals['_COMMUNICATOR']._serialized_end=375
# @@protoc_insertion_point(module_scope)
